### ISSUE TITLE
Scarlet/Violet DLC Regression Checklist

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#154]
Make sure everything still works after DLC lands:

**General:**
- [x] Mass Purchase
- [x] Mass Release
- [x] Autonomous Ball Thrower
- [x] Stats Reset
- [x] Size Checker
- [x] Clothing Buyer
- [x] Self Box Trade
- [x] Sandwich Maker

**Farming:**
- [x] LP Farmer
- [x] Gimmighoul Roaming Farmer
- [x] Gimmighoul Chest Farmer
- [x] Auction Farmer
- [x] ESP Training
- [x] Tournament Farmer

**Eggs:**
- [x] Egg Fetcher
- [x] Egg Hatcher
- [x] Egg Autonomous

**Tera Raids:**
- [x] Auto-Host
- [x] Tera Self-Farmer
- [x] Tera Multi-Farmer
- [x] Tera Roller

**Fast Code Entry:**
- [x] Fast Code Entry
- [x] Clipboard Fast Code Entry
- [x] Video Fast Code Entry

**Shiny Hunting:**
- [x] Shiny Hunt - Area Zero Platform

**Developer Tools:**
- [x] Sound Listener

**Comment by Mysticial** [comment]
The map detector is broken. This affects:

- Chest Farmer
- Tourney Farmer (fly back on loss)
- Platform Bot (platform reset)
- Eggs (fly back)

Green Pokemon summary has been fixed.
