### ISSUE TITLE
Version 0.40 Checklist

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#158]
- [ ] Test the Stats reset (new features)
- [x] Test the bloodmoon Ursaluna stats reset (new program)
- [x] Test tera battles (Y button changed)
- [x] Test normal battle menu (Y button changed)
- [x] Test Eggs (Y button changed, box operations need it)
- [x] Picnics (Y button changed)
- [x] Tera Roller (Y button changed)
