### ISSUE TITLE
Version 0.42 Checklist 

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#163]
Big refactor to the stats filter tables. We need to retest these before release:

- [x] SwSh Egg Autonomous
- [x] BDSP Egg Autonomous
- [x] SV Egg Autonomous
- [x] SV Stats Reset
- [x] SV Bloodmoon Ursaluna

Ursaluna is the new big feature as it uses the new IV range filter. We need to run this until we can prove that it correctly detects the VGC 00 case.
