### ISSUE TITLE
Fye's berry tree program with sound.

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#74]
- [x] Implement program.
- [x] Add stats tracking and encounter detection. (https://github.com/PokemonAutomation/ComputerControl/issues/77)
- [x] Add a wiki. (https://github.com/PokemonAutomation/ComputerControl/issues/78)
- [x] Test by 2 different people with different capture cards.
- [x] Add stats tracking and encounter detection. (https://github.com/PokemonAutomation/ComputerControl/issues/77)
- [ ] Make the rustle detector more reliable. See if we can fix it with a low-pass filter.

**Comment by Mysticial** [comment]
- [x] Implement program.
- [x] Add stats tracking and encounter detection. (https://github.com/PokemonAutomation/ComputerControl/issues/77)
- [ ] Add a wiki.
- [ ] Test by 2 different people with different capture cards.
